name = "Doors"
license = "MIT"
licenselink = "https://github.com/zzzmisa/hugo-theme-doors/blob/master/LICENSE"
description = "Single page theme for links to your works"

homepage = "https://github.com/zzzmisa/hugo-theme-doors"
demosite = "https://zzzmisa.com"

tags = ["contact", "gallery", "landing", "light", "minimal", "multilingual", "personal", "portfolio"]
features = ["google-tag-manager", "multilingual", "responsive"]

[author]
  name = "zzzmisa"
  homepage = "https://zzzmisa.com"
